[workspace]
members = [
    "xaynet",
    "xaynet-core",
    # "xaynet-ffi",
    "xaynet-macros",
    "xaynet-server",
    "xaynet-sdk",

    # internals
    "benches",
    "examples",
]

[workspace.metadata]
# minimum supported rust version
msrv = "1.46.0"
