[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
xaynet-client = { path = "../xaynet-client" }
xaynet-core = { path = "../xaynet-core" }
tracing = "0.1.16"
structopt = "0.3"
tracing-subscriber = "0.2.7"
sodiumoxide = "0.2.5"
tokio = { version = "0.2.21" }

[[example]]
name = "test-drive-net"
path = "test-drive-net.rs"

[[example]]
name = "mobile-client"
path = "mobile-client.rs"
