[log]
filter = "xaynet=debug,http=warn,info"

[api]
bind_address = "127.0.0.1:8081"

[pet]
min_sum_count = 1
min_update_count = 3
min_sum_time = 5
min_update_time = 10
max_sum_time = 3600
max_update_time = 3600
sum = 0.5
update = 0.9
expected_participants = 10

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B0"
model_type = "M3"

[model]
size = 4

[metrics]
store_url = "http://influxdb:8086"
store_name = "metrics"
