on:
  issue_comment:
    types: [created]
    
name: DockerHub (PR) with parameters

jobs:
  check_comments:
    name: Check comments for /deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: build_pr
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write
      # Build container
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      # k8s deploy
      - name: build-tag-push
        uses: docker/build-push-action@v2
        id: docker
        with:
          dockerfile: docker/Dockerfile
          build-args: '${{ steps.command.outputs.command-arguments }}'
